### ISSUE TITLE
failed to start Neo4j after  .neo4j.conf  modified 

### ISSUE THREAD

**Issue by camelliazhang** [graphaware/neo4j-to-elasticsearch#73]
After modifying the .neo4j.conf with elastic search, I can not start neo4j anymore. Here is the error:

Starting Neo4j failed: Component 'org.neo4j.server.AbstractNeoServer$ServerComponentsLifecycleAdapter@30776a08' was successfully initialized, but failed to start. Please see attached cause exception.

Here are the plugins I have: 
graphaware-neo4j-to-elasticsearch-3.1.4.49.7.jar	
graphaware-server-community-all-3.1.4.49.jar		
graphaware-uuid-3.1.4.49.14.jar

Any help? Thanks, Na

**Comment by alenegro81** [comment]
I can't see any attachment. Could you attach the entire log?

**Comment by camelliazhang** [comment]
@alenegro81 Thanks for the quick reply. Actually, I am not sure where the log is.
This is the screen shot of the error (and after I pressed OK it's gone). Is debug.log the one?

<img width="1112" alt="screen shot 2017-05-24 at 12 07 05 pm" src="https://cloud.githubusercontent.com/assets/22062584/26421192/fb9fd4ba-4079-11e7-9d91-4331380093ca.png">

**Comment by camelliazhang** [comment]
Installed it on Linux, got the log as following:

2017-05-26 18:04:53.133+0000 INFO  ======== Neo4j 3.2.0 ========
2017-05-26 18:04:53.373+0000 INFO  Starting...
2017-05-26 18:04:54.407+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2017-05-26 18:04:54.465+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@242f135c' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@242f135c' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@242f135c' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:107)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:80)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@242f135c' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /home/nazhang/Downloads/neo4j-community-3.2.0/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:209)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
	at org.neo4j.server.CommunityNeoServer$$Lambda$101/422250493.newGraphDatabase(Unknown Source)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@161b9d38' failed to initialize. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:416)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
	... 10 more
Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.configuration.Settings.setting(Ljava/lang/String;Ljava/util/function/Function;Ljava/lang/String;)Lorg/neo4j/graphdb/config/Setting;
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.<clinit>(RuntimeKernelExtension.java:79)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtensionFactory.newInstance(RuntimeKernelExtensionFactory.java:52)
	at com.graphaware.runtime.bootstrap.RuntimeKernelExtensionFactory.newInstance(RuntimeKernelExtensionFactory.java:30)
	at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:68)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 13 more
2017-05-26 18:04:54.466+0000 INFO  Neo4j Server shutdown initiated by request

**Comment by ikwattro** [comment]
You run neo4j 3.2, there is no 3.2 compatible version yet. See https://github.com/graphaware/neo4j-framework/issues/73

**Comment by camelliazhang** [comment]
@ikwattro , thanks for your reply! Would you please suggest which version combinations should I use for time being?

**Comment by ikwattro** [comment]
You should use neo4j 3.1.4 with the current plugins version

**Comment by chanh** [comment]
@ikwattro Neo4j 3.1.4 isn't available on their website anymore, and GA doesn't seem to work with Neo4j 3.1.5. 

Any workaround?

**Comment by bachmanm** [comment]
Check https://products.graphaware.com/ - 3.1.4 is there

**Comment by chanh** [comment]
@bachmanm GA 3.1.4 is there, but the problem is Neo4J 3.1.4 itself isn't.

**Comment by bachmanm** [comment]
https://neo4j.com/download-thanks/?edition=community&release=3.1.4&flavour=unix

Or use 3.1.5 - is should work, since there shouldn't have been any API changes

**Comment by chanh** [comment]
Getting the following error with 3.1.5, not sure if it's something I did wrong or not:

`Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@56dceab8' was successfully initialized, but failed to start. Please see the attached cause exception "class org.apache.commons.lang3.time.FastDateParser$ISO8601TimeZoneStrategy cannot access its superclass org.apache.commons.lang3.time.FastDateParser$Strategy".`

**Comment by omarlarus** [comment]
Hi @chanh , I tested the Neo4j 3.1.5 CE and it works, on startup, with the plugins:
- graphaware-neo4j-to-elasticsearch-3.1.4.49.7.jar
- graphaware-server-community-all-3.1.4.49.jar
- graphaware-uuid-3.1.4.49.14.jar

So, to solve your problem, we need to known some environment specs:
- is your neo4j 3.1.5 a clear installation, without previous data inside?
- what is you SO and Java version?
- what do you put in the *neo4j.conf* file?
- do you put the jars only in the *"$NEO4J_HOME/plugins"* directory?

Thank you,
Omar

**Comment by chanh** [comment]
I have the same plugin versions as you:

➜  plugins ls
graphaware-neo4j-to-elasticsearch-3.1.4.49.7.jar graphaware-server-community-all-3.1.4.49.jar     graphaware-uuid-3.1.4.49.14.jar


I'm on OSX and have switched between a couple versions by uninstalling and then installing a new version. When I uninstall, the only thing I do besides deleting Neo4J from the Applications folder is delete ~/Documents/Neo4j.

OS: 10.12.5
Java: java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Neo4j.conf: 
https://gist.github.com/chanh/9344cda49ed1eb5e0734df4f89adcedf

Yep I put the plugins in the plugins directory, and there's nothing else in that directory.

Still getting the same error :(

**Comment by omarlarus** [comment]
@chanh can you try to use the *tar* distribution? You can download the 3.1.4 [here](https://neo4j.com/download-thanks/?edition=community&release=3.1.4&flavour=unix) and the 3.1.5 [here](https://neo4j.com/download-thanks/?edition=community&release=3.1.5&flavour=unix). You have to wait some seconds before the download starts.
The installation is very simple as described [here](https://neo4j.com/docs/operations-manual/current/installation/osx/#osx-console).

Thanks

**Comment by vvavepacket** [comment]
I also encounter the same issue as above..

```
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@5eedd4e9' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
        ... 134 more
Caused by: java.lang.IllegalAccessError: class org.apache.commons.lang3.time.FastDateParser$CaseInsensitiveTextStrategy cannot access its superclass org.apache.commons.lang3.time.FastDateParser$Strategy
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:138)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:115)
        at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
        at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:89)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:80)
        at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:206)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        ... 136 more
cannot access its superclass org.apache.commons.lang3.time.FastDateParser$Strategy
```

**Comment by ptclarke** [comment]
Did anyone get a resolution on this? I get the same error with my own plugin when I introduce a component with an apache commons configuration dependency so I think this is a conflict between dependencies in neo4j and my plugin. Remove the component and the database starts up fine. Now looking to remove the conflict as I need the component. Has anyone managed to do this for graphaware?

Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@54069a1c' was successfully initialized, but failed to start. Please see the attached cause exception "class org.apache.commons.lang3.time.FastDateParser$5 cannot access its superclass org.apache.commons.lang3.time.FastDateParser$NumberStrategy".

**Comment by ikwattro** [comment]
We didn't got time to look close enough to it yet, thanks however for a good starting point.

**Comment by ptclarke** [comment]
Thanks. Resolved my problem by reverting to apache-commons-configuration 1.10. There were 2 conflicts with configuration 2.2 dependencies, commons-lang and commons-beanutils, I could get around commons-lang by using an earlier release of configuration 2.x but commons-beanutils resulted in run time error that I could not resolve.

**Comment by ikwattro** [comment]
interesting, can you try if you can have your plugin + neo4j community + framework + APOC running together

I have no issue with my custom extensions, only with apoc. But I dont have apache commons in my extensions

**Comment by ptclarke** [comment]
apologies @ikwattro I will not have time to test further scenarios. In your situation the question for me would be do APOC and/ or the framework have commons-lang dependencies that conflict with the commons lang release embedded in the neo4j release that you are running?

**Comment by ikwattro** [comment]
Ok so the issue has been fixed by https://github.com/graphaware/neo4j-framework/pull/85
